name: push_release

on:
  push:
    tags:
      - "*-release"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Extract Tag Name
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Building release for tag: ${GITHUB_REF#refs/tags/}"

      - name: Wait On Linux Build
        uses: tomchv/wait-my-workflow@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Shared Library'
          ref: ${{ github.sha }}
          intervalSeconds: 30
          timeoutSeconds: 3600
          workflow: build_linux.yml

      - name: Wait On macOS Intel Build
        uses: tomchv/wait-my-workflow@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Intel (x86_64) DMG'
          ref: ${{ github.sha }}
          intervalSeconds: 30
          timeoutSeconds: 3600
          workflow: build_osx.yml

      - name: Wait On macOS Apple Silicon Build
        uses: tomchv/wait-my-workflow@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Apple Silicon (arm64) DMG'
          ref: ${{ github.sha }}
          intervalSeconds: 30
          timeoutSeconds: 3600
          workflow: build_osx.yml

      - name: Wait On Windows Build
        uses: tomchv/wait-my-workflow@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Shared Library'
          ref: ${{ github.sha }}
          intervalSeconds: 60
          timeoutSeconds: 3600
          workflow: build_windows.yml

      - name: Download Artifacts From Linux Build
        id: download-linux-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: build_linux.yml
            workflow_conclusion: success
            path: artifacts/linux
            allow_forks: false
            name: projectm-linux-shared-latest
            workflow_search: true

      - name: Create Linux Package
        run: |
          cd ${{ github.workspace }}/artifacts/linux
          tar -czvf projectm-linux-x64.tar.gz *
          mv projectm-linux-x64.tar.gz ${{ github.workspace }}/projectm-linux-x64-${{ env.TAG }}.tar.gz

      - name: Download Intel DMG From macOS Build
        id: download-osx-dmg-intel
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build_osx.yml
          workflow_conclusion: success
          path: artifacts/macos-intel
          allow_forks: false
          name: projectm-osx-dmg-intel
          workflow_search: true

      - name: Download Apple Silicon DMG From macOS Build
        id: download-osx-dmg-arm64
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build_osx.yml
          workflow_conclusion: success
          path: artifacts/macos-arm64
          allow_forks: false
          name: projectm-osx-dmg-arm64
          workflow_search: true

      - name: Prepare macOS DMGs for Release
        run: |
          mv ${{ github.workspace }}/artifacts/macos-intel/projectM-v4.1.4-macOS-Intel.dmg ${{ github.workspace }}/projectM-macOS-Intel-${{ env.TAG }}.dmg
          mv ${{ github.workspace }}/artifacts/macos-arm64/projectM-v4.1.4-macOS-AppleSilicon.dmg ${{ github.workspace }}/projectM-macOS-AppleSilicon-${{ env.TAG }}.dmg

      - name: Download Artifacts From Windows Build
        id: download-windows-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build_windows.yml
          workflow_conclusion: success
          path: artifacts/windows
          skip_unpack: true
          allow_forks: false
          name: projectm-windows-shared-latest
          workflow_search: true

      - name: Create Windows Package
        run: |
          mv ${{ github.workspace }}/artifacts/windows/projectm-windows-shared-latest.zip ${{ github.workspace }}/projectm-windows-x64-${{ env.TAG }}.zip

      - name: Display Ready Packages
        run: |
          ls -la ${{ github.workspace }}

      # - name: Build Changelog
      #   id: github_release
      #   uses: mikepenz/release-changelog-builder-action@v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          # body: |
          #   ${{steps.github_release.outputs.changelog}}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            projectm-linux-x64-${{ env.TAG }}.tar.gz
            projectM-macOS-Intel-${{ env.TAG }}.dmg
            projectM-macOS-AppleSilicon-${{ env.TAG }}.dmg
            projectm-windows-x64-${{ env.TAG }}.zip
            